name: Build host tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: sudo apt-get install -y libusb-1.0-0-dev zlib1g-dev libfdt-dev
    - name: make
      run: make tools misc
    - name: make check
      run: make check
# actions
